*** Settings ***
Resource    ../../resources/page_objects/login.resource
Resource    ../../resources/page_objects/header.resource
Resource    ../../resources/page_objects/home.resource
Resource    ../../resources/page_objects/search_results.resource
Resource    ../../resources/step_definitions/step_login.resource
Resource    ../../resources/step_definitions/step_search.resource
Resource    ../../resources/setup_teardown.resource